"""Update user and habit models

Revision ID: 5d195650e856
Revises: d8c9358c404f
Create Date: 2025-09-09 17:40:22.653570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d195650e856'
down_revision: Union[str, Sequence[str], None] = 'd8c9358c404f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False, server_default="1"))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False, server_default="1"))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'level')
    op.drop_column('users', 'xp')
    op.drop_column('habits', 'frequency')
    # ### end Alembic commands ###
